---
kind: pipeline
type: docker
name: python-3-6

steps:
- name: tests
  image: python:3.6
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - pip install -r requirements.txt
  - cp /tmp/cache/test-config.py /drone/src/config.py
  - pytest

volumes:
- name: cache
  host:
    path: /tests/iheart-2-sp

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: docker
name: python-3-7

steps:
- name: tests
  image: python:3.7
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - pip install -r requirements.txt
  - cp /tmp/cache/test-config.py /drone/src/config.py
  - pytest

volumes:
- name: cache
  host:
    path: /tests/iheart-2-sp

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: docker
name: python-3-8

steps:
- name: tests
  image: python:3.8
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - pip install -r requirements.txt
  - cp /tmp/cache/test-config.py /drone/src/config.py
  - coverage run -m pytest
  - coverage xml
- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - coverage.xml

volumes:
- name: cache
  host:
    path: /tests/iheart-2-sp

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
    - bash /home/updatePythonRepo.sh iheart-2-sp

trigger:
  event:
  - promote
  target:
  - production
